version: '2'

services:

  rabbit1:
    image: .
    ports:
      - "15672:15672"
    volumes:
      - 'rabbit1_data:/bitnami'

  rabbit2:
    image: .
    links:
      - rabbit1
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@rabbit2
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbit1
      - RABBITMQ_ERLANG_COOKIE=s3cr3tc00ki3
    volumes:
      - 'rabbit2_data:/bitnami'

  rabbit3:
    image: .
    links:
      - rabbit1
      - rabbit2
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@rabbit3
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbit1
      - RABBITMQ_ERLANG_COOKIE=s3cr3tc00ki3
    volumes:
      - 'rabbit3_data:/bitnami'

volumes:
  rabbit1_data:
    driver: local
  rabbit2_data:
    driver: local
  rabbit3_data:
    driver: local
